# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-10 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0002_auto_20170710_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='mister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hola', models.CharField(max_length=10)),
            ],
        ),
    ]
