# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0005_auto_20170710_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='author',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='img',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
