# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookswap', '0006_auto_20170712_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='available',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
